# Generated by Django 3.2 on 2026-02-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rustdesdevice_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='rustdesktoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='rustdesktag',
            name='profile_guid',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='地址簿GUID'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='password',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='共享密码'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='device_group_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='设备组'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='login_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='登录账号'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='same_server',
            field=models.BooleanField(default=False, verbose_name='同服务器'),
        ),
        migrations.AddField(
            model_name='rustdeskpeer',
            name='profile_guid',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='地址簿GUID'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='归属用户'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='device_group_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='设备组'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='strategy_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='策略名称'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='address_book_name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='地址簿名称'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='address_book_tag',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='地址簿标签'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='address_book_alias',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='地址簿别名'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='address_book_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='地址簿密码'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='address_book_note',
            field=models.TextField(blank=True, default='', verbose_name='地址簿备注'),
        ),
        migrations.AddField(
            model_name='connlog',
            name='conn_type',
            field=models.IntegerField(null=True, verbose_name='Conn Type'),
        ),
        migrations.CreateModel(
            name='StrategyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='策略名称')),
                ('config_options', models.TextField(blank=True, default='', verbose_name='配置项')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略列表',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AddressBookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=60, unique=True, verbose_name='地址簿GUID')),
                ('name', models.CharField(max_length=60, verbose_name='地址簿名称')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('rule', models.IntegerField(default=1, verbose_name='共享权限')),
                ('info', models.TextField(blank=True, default='', verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '地址簿',
                'verbose_name_plural': '地址簿列表',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AddressBookShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.IntegerField(default=1, verbose_name='共享权限')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.addressbookprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '地址簿共享',
                'verbose_name_plural': '地址簿共享列表',
                'unique_together': {('profile', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=64, unique=True, verbose_name='GUID')),
                ('peer_id', models.CharField(db_index=True, max_length=20, verbose_name='Peer ID')),
                ('session_id', models.CharField(db_index=True, max_length=60, verbose_name='Session ID')),
                ('conn_type', models.IntegerField(default=0, verbose_name='Conn Type')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': '审计会话',
                'verbose_name_plural': '审计会话列表',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(default=0, verbose_name='Type')),
                ('info', models.TextField(blank=True, default='', verbose_name='Info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志列表',
                'ordering': ('-created_at',),
            },
        ),
    ]
