# Generated by Django 6.0.7 on 2026-07-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_modern_contracts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connlog',
            options={'ordering': ('-conn_start',), 'verbose_name': '连接日志', 'verbose_name_plural': '连接日志列表'},
        ),
        migrations.AlterModelOptions(
            name='filelog',
            options={'ordering': ('-logged_at',), 'verbose_name': '文件传输日志', 'verbose_name_plural': '文件传输日志列表'},
        ),
        migrations.AlterModelOptions(
            name='rustdeskpeer',
            options={'ordering': ('-username',), 'verbose_name': '客户端', 'verbose_name_plural': '客户端列表'},
        ),
        migrations.AlterModelOptions(
            name='rustdesktag',
            options={'ordering': ('-uid',), 'verbose_name': '标签', 'verbose_name_plural': '标签列表'},
        ),
        migrations.AlterModelOptions(
            name='rustdesktoken',
            options={'ordering': ('-username',), 'verbose_name': '令牌', 'verbose_name_plural': '令牌列表'},
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='rid',
            field=models.CharField(max_length=16, verbose_name='Camellia ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rid',
            field=models.CharField(max_length=16, verbose_name='Camellia ID'),
        ),
    ]
