# Generated by Django 6.0.7 on 2026-07-26 15:56

from django.db import migrations, models


def purge_plaintext_tokens(apps, schema_editor):
    """Access tokens are now stored hashed (SHA-256); pre-existing plaintext
    rows can never match a hashed lookup, so drop them. Clients simply
    re-authenticate on their next request."""
    apps.get_model('api', 'RustDeskToken').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_connlog_options_alter_filelog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=64, verbose_name='IP')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': '失败登录',
                'verbose_name_plural': '失败登录列表',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OidcPendingAuth',
            fields=[
                ('state', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='State')),
                ('provider', models.CharField(max_length=64, verbose_name='Provider')),
                ('rid', models.CharField(blank=True, default='', max_length=16, verbose_name='Camellia ID')),
                ('device_uuid', models.CharField(blank=True, default='', max_length=60, verbose_name='Device UUID')),
                ('device_info', models.TextField(blank=True, default='', verbose_name='Device Info')),
                ('status', models.CharField(db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('body', models.JSONField(blank=True, null=True, verbose_name='Auth Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'OIDC待处理授权',
                'verbose_name_plural': 'OIDC待处理授权列表',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(purge_plaintext_tokens, migrations.RunPython.noop),
    ]
