# Generated by Django 6.0.7 on 2026-07-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_loginattempt_oidcpendingauth'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rustdesktoken',
            constraint=models.UniqueConstraint(fields=('uid', 'rid', 'uuid'), name='unique_token_per_device'),
        ),
    ]
